layout_spectrum: 0.8545612
typography_spectrum: 0.3090191
color:
  lightness: 0.7280406
  brandStrength: 0.1238465
  saturation: 0.3920504
  rhythmicContrast: 0.7517254
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: SiteB
